### ISSUE TITLE
setup.json not in MANIFEST.in

### ISSUE THREAD

**Issue by chrisjsewell** [dev-zero/aiida-gaussian-datatypes#5]
Heya @dev-zero, could you release another version to PyPI, with setup.json included in the `MANIFEST.in` please. Since at present it is not possible to install from the distributed source 😢

**Comment by chrisjsewell** [comment]
Thnaks @dev-zero! I don't see a new release on https://pypi.org/project/aiida-gaussian-datatypes/#history yet, were you also intending to do this?

**Comment by dev-zero** [comment]
@chrisjsewell Patience you must have. Release done now.

**Comment by chrisjsewell** [comment]
![image](https://user-images.githubusercontent.com/2997570/180486084-0ce97a0e-59d9-4851-875b-9b74169be8a8.png)

**Comment by chrisjsewell** [comment]
cheers
